# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  get_files:
    name: run_on_pr_or_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Modified files
        run: |
          case '${{ github.event_name }}' in
            push)
              changedFiles=$(git diff --name-only --diff-filter=d "${GITHUB_EVENT_BEFORE}" "${GITHUB_SHA}")
              ;;
            pull_request)
              changedFiles=$(git diff --name-only --diff-filter=d "${GITHUB_EVENT_BASE_REF}" "${GITHUB_EVENT_HEAD_REF}")
              ;;
          esac
          echo "$changedFiles"
