name: Validate Additions

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for deletions or modifications
        run: |
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep -E '^[D|M]' && exit 1 || exit 0
